version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: ecofirst-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://admin:123456@db:5432/ecofirst"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: ecofirst-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecofirst
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
